#!/bin/sh
# Ensure the script exits on any error
set -e

# Get the directory of the current script
dir="$(cd "$(dirname "$0")" && pwd)"

# Execute the no_todos script with the correct path
"$dir/scripts/no_todos"
